SapremaMain/Controllers/AsanaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SapremaMain.Models;
using SapremaMain.Models.MeditationViewModels;
using SapremaMain.Services;
using SapremaMain.DAL;
using SapremaMain.Models.ProfileViewModels;

namespace SapremaMain.Controllers
{
    public class AsanaController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;
        private readonly string _externalCookieScheme;

        public AsanaController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IOptions<IdentityCookieOptions> identityCookieOptions,
            IEmailSender emailSender,
            ISmsSender smsSender,
            ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _externalCookieScheme = identityCookieOptions.Value.ExternalCookieAuthenticationScheme;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<AccountController>();
        }
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Store()
        {
            return View();
        }

        public async Task<IActionResult> MyGroups()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            List<MyGroupsViewModel> myGroupsList = new List<MyGroupsViewModel>();

                MyGroupsViewModel myGroupsViewModel = new MyGroupsViewModel()
                {
                    GroupName = "Dolphins",
                    GroupTeacher = "John",
                    GroupDescription = "Alpha ghroup",
                    GroupId = "1"
        };
                myGroupsList.Add(myGroupsViewModel);

            MyGroupsViewModel myGroupsViewModel2 = new MyGroupsViewModel()
            {
                GroupName = "BBQ Yoga",
                GroupTeacher = "Che",
                GroupDescription = "BBQ + yoghurt",
                GroupId = "2"
            };
            myGroupsList.Add(myGroupsViewModel2);

            MyGroupsViewModel myGroupsViewModel3 = new MyGroupsViewModel()
            {
                GroupName = "Twister",
                GroupTeacher = "Mike",
                GroupDescription = "hi nrg yoga yo",
                GroupId = "3"
        };
            myGroupsList.Add(myGroupsViewModel3);

            //List<MyGroupsViewModel> myGroupsList = new Get().GetMyGroups(user.Id);
            return View(myGroupsList);
        }

        // GET: Profile/Details/5
        public IActionResult AddGroup()
        {
            return View();
        }
    }
}

SapremaMain/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SapremaMain.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

SapremaMain/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

SapremaMain/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SapremaMain/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using SapremaMain.Models

@{
    ViewData["Title"] = "Home Page";
}

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-1 col-lg-4 col-lg-offset-1">
            <img class="circle-holder" src="~/images/buddha.svg" alt="Buddha" />
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 menu-text">
            <h1>ASANA</h1>
            <h2>Be at one with your body with a range of our classes</h2>
            <p><a href="#primary-modal" data-toggle="modal" class="menu-link" id="menu-classes-btn">Classes:</a> Create your own or generate a random class</p>
            <p><a href="#" class="menu-link" id="menu-classes-saved-btn">Saved Classes:</a> Practice your saved classes</p>
            <p><a href="~/Profile/MyGroups"  class="menu-link" id="menu-classes-groups-btn">Groups:</a> Manage your grououps</p>
            <p><a asp-area="" asp-controller="Asana" asp-action="Store" class="menu-link" id="menu-classes-store-btn">Store:</a> Search for classes or groups</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-md-offset-1 col-lg-4 col-lg-offset-1">
            <img class="circle-holder" src="~/images/om.svg" alt="Om Symbol" />
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 menu-text">
            <h1>MEDITATION</h1>
            <h2>Relax your mind with a range of our meditations</h2>
            <p><a asp-area="" asp-controller="Meditation" asp-action="Meditations" class="menu-link" id="menu-meditation-btn">Meditations:</a> Play meditations you have bookmarked</p>
            <p><a asp-area="" asp-controller="Meditation" asp-action="BreathTimer" class="menu-link" id="menu-meditation-breath-btn">Breath Timer:</a> Practice your breath using a timer</p>
            @if (User.IsInRole("Admin"))
            {
                <p><a asp-area="" asp-controller="Meditation" asp-action="ManageMeditations" class="menu-link">Manage Meditation:</a> Upload meditations to the store</p>
            }
            <p><a asp-area="" asp-controller="Meditation" asp-action="MeditationStore" class="menu-link" id="menu-meditation-store-btn">Store:</a> Search for meditations</p>
        </div>
    </div>
}
else
{
    <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2"><img id="landing-logo" src="~/images/logoBorder.svg" alt="Saprema logo with border" width="100%" /> </div>
}