SapremaMain/Models/MeditationViewModels/ManageMeditationsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;

namespace SapremaMain.Models.MeditationViewModels
{
    public class ManageMeditationsViewModel
    {
        public List<ManageMeditationItem> MeditationItems { get; set; }

        public string MeditationId { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        [Display(Name = "Meditate Theme")]
        public string MeditateTheme { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Text)]
        [Display(Name = "Meditation Name")]
        public string MeditateName { get; set; }

        public string ImageUrl { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 4)]
        [DataType(DataType.Text)]
        [Display(Name = "Meditation Type")]
        public string MeditateType { get; set; }

        public string MeditateCreator { get; set; }

        //why you broke?
        //[FileExtensions(Extensions = "jpg,jpeg")]
        public IFormFile MeditateAudio { get; set; }

        public IFormFile MeditateImage { get; set; }
    }

    public class ManageMeditationItem
    {
        public Guid MeditationId { get; set; }
        public string MeditationName { get; set; }
    }
}

SapremaMain/Models/MeditationViewModels/MeditationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SapremaMain.Models.MeditationViewModels
{
    public class MeditationViewModel
    {
        public string MeditateName { get; set; }

        public string MeditateTheme { get; set; }

        public string MeditateType { get; set; }

        public string ImageUrl { get; set; }

        public string ImageName { get; set; }
    }
}

SapremaMain/Models/MeditationViewModels/MeditationsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;

namespace SapremaMain.Models.MeditationViewModels
{
    public class MeditationsViewModel
    {
        public Guid MeditationId { get; set; }
        public string MeditationName { get; set; }
        public string MeditationTheme { get; set; }
        public string MeditationType { get; set; }
    }
}

SapremaMain/Models/MeditationViewModels/PlayMeditationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SapremaMain.Models.MeditationViewModels
{
    public class PlayMeditationViewModel
    {
        public Guid MeditationId { get; set; }

        public string MeditationName { get; set; }

        public Guid? MeditationImage { get; set; }

        public string MedPath { get; set; }
    }
}

SapremaMain/Controllers/MeditationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SapremaMain.Models;
using SapremaMain.Models.MeditationViewModels;
using SapremaMain.Services;
using SapremaMain.DAL;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SapremaMain.Controllers
{
    public class MeditationController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public MeditationController(
            UserManager<ApplicationUser> userManager,
            IHostingEnvironment hostingEnvironment,
            ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        //remove in production
        [AllowAnonymous]
        public IActionResult ManageMeditations(string returnUrl = null)
        {
            ManageMeditationsViewModel manageMeditaionsViewModel = new Get().GetTeachers();
            ViewData["ReturnUrl"] = returnUrl;
            return View(manageMeditaionsViewModel);
        }

        [HttpGet]
        //remove in production
        [AllowAnonymous]
        public IActionResult PlayMeditation(string MeditationId)
        {
            Guid pareseMedId = Guid.Parse(MeditationId);
            PlayMeditationViewModel playMeditationViewModel = new Get().GetPlayMeditation(pareseMedId);
            return View(playMeditationViewModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult ReviewMediation(string MeditationId)
        {
            return PartialView();
        }

        [HttpGet]
        //remove in production
        [AllowAnonymous]
        public IActionResult Meditations(string returnUrl = null)
        {
            var user = _userManager.GetUserId(User);
            List<MeditationsViewModel> meditationsVMList = new Get().GetUsersMeditations(user);
            ViewData["ReturnUrl"] = returnUrl;
            return View(meditationsVMList);
        }

        [HttpGet]
        //remove in production
        [AllowAnonymous]
        public IActionResult MeditationStore(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        public IActionResult ManageMeditations(ManageMeditationsViewModel manageMeditationsViewModel)
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            var currentUserName = currentUser.Identity.Name;

            if (String.IsNullOrEmpty(manageMeditationsViewModel.MeditationId))
            {
                var meditationSavedUpdated = new DAL.Create().CreateMeditation(manageMeditationsViewModel.MeditateName, manageMeditationsViewModel.MeditateTheme, currentUserName, manageMeditationsViewModel.MeditateType, _hostingEnvironment, manageMeditationsViewModel.MeditateImage, manageMeditationsViewModel.MeditateAudio);
                ManageMeditationsViewModel newManageMeditaionsViewModel = new Get().GetTeachers();
                return View(newManageMeditaionsViewModel);
            }


            if (ModelState.IsValid)
            {
                var meditationSavedUpdated = new DAL.Create().UpdateMeditation(manageMeditationsViewModel.MeditationId, manageMeditationsViewModel.MeditateName, manageMeditationsViewModel.MeditateTheme, currentUserName, manageMeditationsViewModel.MeditateType, _hostingEnvironment, manageMeditationsViewModel.MeditateImage, manageMeditationsViewModel.MeditateAudio);
                ManageMeditationsViewModel newManageMeditaionsViewModel = new Get().GetTeachers();
                return View(newManageMeditaionsViewModel);
            }

            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult GetMeditationRecord()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult GetMeditationRecord([FromBody] string meditationId)
        {
            ManageMeditationsViewModel manageMeditationsViewModel = new Get().GetMeditation(meditationId);
            return View(manageMeditationsViewModel);
        }

        //[HttpPost]
        //[AllowAnonymous]
        //public IActionResult GetMeditationRecord(ManageMeditationsViewModel manageMeditationsViewModel)
        //{
        //    var foo = manageMeditationsViewModel;
        //    //GetMeditationRecordViewModel getMeditationRecordViewModel = new Get().GetMeditation(meditationId);
        //    return View(manageMeditationsViewModel);
        //}

    }
}

SapremaMain/Views/Meditation/BreathTimer.cshtml
<div class="container-fluid text-center">
    <h1 class="page-header">Breath Timer</h1>
    <div class="row col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-ms-offset-2 col-lg-8 col-lg-offset-2">
        <div class="col-xs-12 col-sm-2 col-md-1 col-lg-1 breath-pad">
            Inhale
        </div>
        <div class="col-xs-12 col-sm-3 col-md-4 col-lg-4">
            <input type="number" id="inhale" min="1" max="30" value="1"><br />
        </div>
        <div class="col-xs-12 col-sm-2 col-md-1 col-lg-1">
            Hold
        </div>
        <div class="col-xs-12 col-sm-3 col-md-4 col-lg-4">
            <input type="number" id="inHold" min="0" max="30" value="0"><br />
        </div>
    </div>
    <div class="row col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-ms-offset-2 col-lg-8 col-lg-offset-2 breath-timer-lower">
        <div class="col-xs-12 col-sm-2 col-md-1 col-lg-1 breath-pad">
            Exhale
        </div>
        <div class="col-xs-12 col-sm-3 col-md-4 col-lg-4">
            <input type="number" id="exhale" min="1" max="30" value="1"><br />
        </div>
        <div class="col-xs-12 col-sm-2 col-md-1 col-lg-1">
            Hold
        </div>
        <div class="col-xs-12 col-sm-3 col-md-4 col-lg-4">
            <input type="number" id="outHold" min="0" max="30" value="0"><br>
        </div>
    </div>
    <div class="row col-xs-12 breath-timer-lower center-block">
        <button class="btn btn-primary" onclick="clickThis(), showBreath()">Begin</button>
    </div>
</div>

<div id="breath-display" class="overlay">
    <div class="overlay-content">
        <img id="play-meditation-image" class="img-responsive center-block" width="25%" src="../images/logo.svg" /><br />
        <p class="player-text" id="breath-text"></p>
        <div>
            <input id="vol-control" type="range" min="0" max="100" step="1" width="100px" value="100" oninput="SetVolume(this.value)" onchange="SetVolume(this.value)"></input>
            <a href="javascript:void(0)" onclick="hideDisplay()" id="stop-button"><p class="fa fa-stop-circle-o" aria-hidden="true"></p></a> 
        </div>
        
    </div>
</div>

<script type="text/javascript" src="~/js/breathTimer.js"></script>

SapremaMain/Views/Meditation/GetMeditationRecord.cshtml
@model SapremaMain.Models.MeditationViewModels.ManageMeditationsViewModel

@{ 
    Layout = null;
}
<form id="@Model.MeditationId" enctype="multipart/form-data" asp-controller="Meditation" asp-action="ManageMeditations" method="POST" class="form-horizontal">
    <h4>Edit Meditation</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>

    <input asp-for="MeditationId" type="hidden" />

    <div class="form-group">
        <label asp-for="MeditateTheme" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="MeditateTheme" class="form-control" />
            <span asp-validation-for="MeditateTheme" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="MeditateName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="MeditateName" class="form-control" />
            <span asp-validation-for="MeditateName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="MeditateType" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="MeditateType" class="form-control" />
            <span asp-validation-for="MeditateType" class="text-danger"></span>
        </div>
    </div>


    @*<img style="width:80%;height:auto;" src="@Model.ImageUrl"
         alt="default meditation image"
          />*@


    <div class="form-group">
        <div class="col-md-10">
            <p>Upload an image file:</p>
            <input type="file" name="MeditateImage" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <p>Upload an audio file:</p>
            <input type="file" name="MeditateAudio" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Save Meditaion</button>
        </div>
    </div>
</form>

SapremaMain/Views/Meditation/ManageMeditations.cshtml
@model SapremaMain.Models.MeditationViewModels.ManageMeditationsViewModel
<div class="container">
    <h1 class="page-header">Manage Meditations</h1>
</div>

<div>
    <div id="listOfMeditations" class="col-lg-6 scroll-div"" >
        <ul>
            @if (Model.MeditationItems != null && Model.MeditationItems.Count > 0)
            {
                foreach (var meditationItem in @Model.MeditationItems)
                {
                    <li class="teacher-list medItem" data-medId="@meditationItem.MeditationId">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                @meditationItem.MeditationName
                            </div>
                        </div>
                    </li>
                    <hr />
                }

            }
            </ul>
</div>
    <div id="editMed" class="col-lg-6" >
        @Html.Partial("GetMeditationRecord.cshtml");
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

SapremaMain/Views/Meditation/MeditationStore.cshtml
<div class="container">
    <h1 class="page-header">Store</h1>
</div>

SapremaMain/Views/Meditation/Meditations.cshtml
@model List<SapremaMain.Models.MeditationViewModels.MeditationsViewModel>

<div class="container">
    <h1 class="page-header">Meditations</h1>
</div>
<div class="container scroll-div">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">
        <ul>
            @foreach (var vm in Model)
            {
                <li class="teacher-list">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                            @vm.MeditationName
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-5">
                            @vm.MeditationId
                        </div>
                        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                            @vm.MeditationType
                        </div>
                        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-1">
                            <button data-medId="@vm.MeditationId" class="btn btn-default pull-right meditation-list-btn">play</button>
                        </div>
                    </div>
                </li>
                <hr />
            }
        </ul>
    </div>
</div>

@*onclick="location.href='@Url.Action("PlayMeditation", "Meditation", new { MeditationId = vm.MeditationId })'"*@

SapremaMain/Views/Meditation/PlayMeditation.cshtml
@model SapremaMain.Models.MeditationViewModels.PlayMeditationViewModel




<div class="container" onload="startMeditation()">
    <h1 class="page-header">Meditation Player</h1>
    <img id="play-meditation-image" class="img-responsive center-block" width="40%" src="../images/logo.svg"/><br />
    <audio id="meditation-player" autoplay onended="showReviewModal();">
        <source src="~audio/ding.mp3" id="audio-source" type="audio/mpeg" />
    </audio>
    
    <div class="row col-sm-12 col-sm-12 col-md-12 col-lg-12 player-controls">
        <input id="vol-control-main" type="range" min="0" max="100" step="1" width="100px" value="100" oninput="SetVolume(this.value)" onchange="SetVolume(this.value)"></input>
        <a asp-area="" asp-controller="Meditation" asp-action="Meditations" id="stop-button"><p class="fa fa-stop-circle-o" aria-hidden="true"></p></a> 
        <a href="javascript:void(0)" onclick="fullscreen()" id="fullscreen-button"><p class="fa fa-expand" aria-hidden="true"></p></a>
    </div>
</div>

<div id="meditation-fullscreen" class="overlay">
    <div class="overlay-content">
        <p class="player-text" id="meditation-text"></p>
        <img id="play-meditation-image" class="img-responsive center-block" width="25%" src="../images/logo.svg" /><br />
        <div>
            <input id="vol-control-overlay" type="range" min="0" max="100" step="1" width="100px" value="100" oninput="SetVolume(this.value)" onchange="SetVolume(this.value)"></input>
            <a asp-area="" asp-controller="Meditation" asp-action="Meditations" id="stop-button"><p class="fa fa-stop-circle-o" aria-hidden="true"></p></a>
            <a href="javascript:void(0)" onclick="hideDisplay()" id="stop-button"><p class="fa fa-compress" aria-hidden="true"></p></a>
        </div>

    </div>
</div>

<div id="review-modal" class="modal fade" role="dialog">
</div>

<script type="text/javascript" src="~/js/playMeditation.js"></script>
<script>
    var foo = '@Model.MeditationId';
</script>

SapremaMain/Views/Meditation/ReviewMediation.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Review Meditation</h4>
        </div>
        <div class="modal-body container">
            <div class="row">
                Rating:
                <fieldset class="rating">
                    <input type="radio" id="star5" name="rating" value="5" /><label class="full" for="star5" title="5 stars"></label>
                    <input type="radio" id="star4half" name="rating" value="4 and a half" /><label class="half" for="star4half" title="4.5 stars"></label>
                    <input type="radio" id="star4" name="rating" value="4" /><label class="full" for="star4" title="4 stars"></label>
                    <input type="radio" id="star3half" name="rating" value="3 and a half" /><label class="half" for="star3half" title="3.5 stars"></label>
                    <input type="radio" id="star3" name="rating" value="3" /><label class="full" for="star3" title="3 stars"></label>
                    <input type="radio" id="star2half" name="rating" value="2 and a half" /><label class="half" for="star2half" title=".5 stars"></label>
                    <input type="radio" id="star2" name="rating" value="2" /><label class="full" for="star2" title="2 stars"></label>
                    <input type="radio" id="star1half" name="rating" value="1 and a half" /><label class="half" for="star1half" title="1.5 stars"></label>
                    <input type="radio" id="star1" name="rating" value="1" /><label class="full" for="star1" title="1 star"></label>
                    <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="0.5 stars"></label>
                </fieldset>
            </div>
            <div class="row">
                <textarea rows="4" cols="50" placeholder="comment"></textarea>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" id="meditation-review-btn" class="btn btn-default">Review</button>
            <button type="button" id="skip-review" onclick="skipReview()" class="btn btn-default">Skip</button>
        </div>

    </div>
</div>